[package]
name = "TMWT"
version = "0.1.0"
edition = "2021"
authors = ["Steven Schiavone <steven.schiavone@gmail.com>"]
description = "A TUI application for Windows system settings"
license = "MIT"

[dependencies]
ratatui = "0.26"
crossterm = "0.27"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
windows = { version = "0.56", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_System_Registry",
    "Win32_System_Power",
    "Win32_System_SystemInformation",
    "Win32_NetworkManagement_WiFi",
    "Win32_NetworkManagement_IpHelper",
    "Win32_Media_Audio",
    "Win32_Media_Audio_Endpoints",
    "Win32_System_Com"
]}
fuzzy-matcher = "0.3"
dirs = "5.0"
anyhow = "1.0"
once_cell = "1.19"

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
strip = true